import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class Calculator extends javax.swing.JFrame implements KeyListener {
	/**
	 * @author McCaulley Granville
	 */
	
    double num, ans, temp;
    int calculation;
    boolean adding,subtracting,multiplying,dividing = false;
    /**
     * Creates new form Calculator
     *  
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public Calculator() {
        initComponents();
        jRadioButtonON.setEnabled(false);
    }

    public void arithmetic_operation(){
        switch(calculation)
        {
            case 1:
            	if (adding == false) {
            		temp = Double.parseDouble(jTextField1.getText());
            		ans = num + Double.parseDouble(jTextField1.getText());
                	jTextField1.setText(Double.toString(ans));
            	} else {
            		ans = Double.parseDouble(jTextField1.getText()) + temp ;
            		jTextField1.setText(Double.toString(ans));
            	}
                adding = true;
                break;
            case 2:
            	if (subtracting == false) {
            		temp = Double.parseDouble(jTextField1.getText());
            		ans = num - Double.parseDouble(jTextField1.getText());
                	jTextField1.setText(Double.toString(ans));
            	} else {
            		ans = Double.parseDouble(jTextField1.getText()) - temp ;
            		jTextField1.setText(Double.toString(ans));
            	}
                subtracting = true;
                break;
            case 3:
                ans = num * Double.parseDouble(jTextField1.getText());
                if (multiplying == false) {
            		temp = Double.parseDouble(jTextField1.getText());
            		ans = num * Double.parseDouble(jTextField1.getText());
                	jTextField1.setText(Double.toString(ans));
            	} else {
            		ans = Double.parseDouble(jTextField1.getText()) * temp ;
            		jTextField1.setText(Double.toString(ans));
            	}
                multiplying = true;
                break;
            case 4:
            	if (dividing == false) {
            		temp = Double.parseDouble(jTextField1.getText());
            		ans = num / Double.parseDouble(jTextField1.getText());
                	jTextField1.setText(Double.toString(ans));
            	} else {
            		ans = Double.parseDouble(jTextField1.getText()) / temp ;
            		jTextField1.setText(Double.toString(ans));
            	}
                dividing = true;
                break;
        }
    }
    
    @SuppressWarnings("unchecked")                         
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButtonON = new javax.swing.JRadioButton();
        jRadioButtonOFF = new javax.swing.JRadioButton();
        jButtonBS = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonDec = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jLabelInputPreview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(this);;

        buttonGroup1.add(jRadioButtonON);
        jRadioButtonON.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jRadioButtonON.setText("ON");
        jRadioButtonON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonONActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonOFF);
        jRadioButtonOFF.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jRadioButtonOFF.setText("OFF");
        jRadioButtonOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOFFActionPerformed(evt);
            }
        });

        jButtonBS.setText("<--");
        jButtonBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBSActionPerformed(evt);
            }
        });

        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("2");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });


        jButtonDec.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonDec.setText(".");
        jButtonDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecActionPerformed(evt);
            }
        });

        jButtonEquals.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jButtonPlus.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonMinus.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButtonMult.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonMult.setText("*");
        jButtonMult.setToolTipText("");
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });


        jButtonDiv.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.setToolTipText("");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jLabelInputPreview.setForeground(new java.awt.Color(255, 51, 51));
        jLabelInputPreview.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInputPreview.setText(" ");
        jLabelInputPreview.setFont(new Font("Times New Roman", Font.BOLD, 11));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonOFF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonON)
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInputPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelInputPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOFF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDiv)
                        .addComponent(jButtonC)
                        .addComponent(jButtonBS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButtonMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButtonMinus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButtonPlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0)
                    .addComponent(jButtonDec)
                    .addComponent(jButtonEquals))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>   

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "0");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "1");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "2");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "3");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }  

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "4");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "5");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }    

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "6");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }
        
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "7");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }    
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "8");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText(jTextField1.getText() + "9");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    } 

    private void jButtonDecActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText() + ".");
        adding = false;
        subtracting = false;
        multiplying = false;
        dividing = false;
    }
    
    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {    
    	if (!jTextField1.getText().isEmpty()) {
	        num = Double.parseDouble(jTextField1.getText());
	        calculation = 1;
	        jTextField1.setText("");
	        jLabelInputPreview.setText(num + " + ");
    	}
    } 

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {    
    	if (!jTextField1.getText().isEmpty()) {
	        num = Double.parseDouble(jTextField1.getText());
	        calculation = 2;
	        jTextField1.setText("");
	        jLabelInputPreview.setText(num + " - ");
        }
    }  

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {
    	if (!jTextField1.getText().isEmpty()) {
	        num = Double.parseDouble(jTextField1.getText());
	        calculation = 3;
	        jTextField1.setText("");
	        jLabelInputPreview.setText(num + " * ");
    	}
    }   

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {
    	if (!jTextField1.getText().isEmpty()) {
	        num = Double.parseDouble(jTextField1.getText());
	        calculation = 4;
	        jTextField1.setText("");
	        jLabelInputPreview.setText(num + " / ");
        }
    }

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        arithmetic_operation();
        jLabelInputPreview.setText(" ");
    }  
    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jTextField1.setText("");
        jLabelInputPreview.setText(" ");
        temp = 0;
    } 

    private void jButtonBSActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (jTextField1.getText().length() > 1) {
        	jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length()-1));
        } else if (jTextField1.getText().length() > 0) {
        	jTextField1.setText("0");
        }
        
    }  
    
    private void jRadioButtonONActionPerformed(java.awt.event.ActionEvent evt) {                                               
        enableButtons();
    } 

    private void jRadioButtonOFFActionPerformed(java.awt.event.ActionEvent evt) {                                                
        disableButtons();
    }                                               

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                                                                                                                  
                                                                                                                                                                                                                                                                                                                    
    public void disableButtons(){
        jRadioButtonON.setEnabled(true);
        jRadioButtonOFF.setEnabled(false);
        jTextField1.setEnabled(false);
        jButton0.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButtonDec.setEnabled(false);
        jButtonPlus.setEnabled(false);
        jButtonMinus.setEnabled(false);
        jButtonMult.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonEquals.setEnabled(false);
    }
    
    public void enableButtons(){
        jRadioButtonOFF.setEnabled(true);
        jRadioButtonON.setEnabled(false);
        jTextField1.setEnabled(true);
        jButton0.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButtonDec.setEnabled(true);
        jButtonPlus.setEnabled(true);
        jButtonMinus.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonEquals.setEnabled(true);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBS;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDec;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JLabel jLabelInputPreview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonOFF;
    private javax.swing.JRadioButton jRadioButtonON;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
	@Override
	public void keyPressed(KeyEvent arg0) {
		if (arg0.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
			jButtonBSActionPerformed(null);
		}
		
		if (arg0.getKeyCode() == KeyEvent.VK_ESCAPE) {
			jButtonCActionPerformed(null);
		}
		
		if (arg0.getKeyCode() == KeyEvent.VK_ENTER) {
			jButtonEqualsActionPerformed(null);
		}
	}

	@Override
	public void keyReleased(KeyEvent arg0) {
	}

	@Override
	public void keyTyped(KeyEvent arg0) {
		if (arg0.getKeyChar() == '1') {
			jButton1ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '2') {
			jButton2ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '3') {
			jButton3ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '4') {
			jButton4ActionPerformed(null);
		}
		if (arg0.getKeyChar() == '5') {
			jButton5ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '6') {
			jButton6ActionPerformed(null);
		}
		if (arg0.getKeyChar() == '7') {
			jButton7ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '8') {
			jButton8ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '9') {
			jButton9ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '0') {
			jButton0ActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '.') {
			jButtonDecActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '+') {
			jButtonPlusActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '-') {
			jButtonMinusActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '*') {
			jButtonMultActionPerformed(null);
		}
		
		if (arg0.getKeyChar() == '/') {
			jButtonDivActionPerformed(null);
		}
	}
}
